name: dpd-php-sdk
services:
  appserver:
    type: php:8.1
    via: cli
    webroot: .
    xdebug: "debug,coverage,develop"
    volumes:
      # Add directory for PhpStorm coverage XML report
      - ./build/coverage/xml/:/opt/phpstorm-coverage/
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  phpunit:
    service: appserver
    description: Run PHPUnit tests
    cmd: "/app/vendor/bin/phpunit"
