name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 7.4, 8.0, 8.1, 8.2 ]

    name: ${{ matrix.os }} / PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run test suite
        env:
          DPD_USERNAME: ${{ secrets.DPD_USERNAME }}
          DPD_PASSWORD: ${{ secrets.DPD_PASSWORD }}
          DPD_COUNTRY_CODE: ${{ vars.DPD_COUNTRY_CODE }}
        run: composer test
